### ISSUE TITLE
Warnings are underlined like errors

### ISSUE THREAD

**Issue by vlourme** [michael-andreuzza/wvsc-serendipity#1]
Hi, I found this small confusing thing: 
<img width="585" alt="Capture d’écran 2021-07-19 à 14 04 57" src="https://user-images.githubusercontent.com/58728578/126157431-88c32a21-b9bc-4833-882f-9868cfc71e1d.png">

This line of code in Go, is not an error, it's a warning from the MongoDB library. Many themes underline this in yellow/orange color to signify a warning. But here, it is really close to the red error-like color.

It is normal or should this be changed?
Thanks 😀

**Comment by michael-andreuzza** [comment]
Oh, that's the pink shade. Let me see what I can do and I push an upodate.

Thank you so much Victor, that was a good catch.

/Mike

**Comment by michael-andreuzza** [comment]
<img width="1243" alt="Screen Shot 2021-07-20 at 00 22 23" src="https://user-images.githubusercontent.com/34077176/126229186-7d802995-2357-4164-9a0e-73a79eef99a6.png">

just pushed the update to the theme, you can try to reload in around 20 minutes? from now.

Let me know what you think.

Thank you.
/Mike

**Comment by vlourme** [comment]
Hi @michael-andreuzza 

Thank you for the quick update, that's better, less confusing!
Good job 👍 

<img width="585" alt="Capture d’écran 2021-07-20 à 10 07 36" src="https://user-images.githubusercontent.com/58728578/126285037-4e65533c-cfd3-4305-93c6-3c1ddc2dab00.png">

**Comment by michael-andreuzza** [comment]
Superb. I am happy that you are happy  :-) have a good one!
