### ISSUE TITLE
Can matched search time be highlighted in different color?

### ISSUE THREAD

**Issue by gregkonush** [michael-andreuzza/wvsc-serendipity#2]
Right now it is highlighted with pink on pink color and it is not really legible.
Is there setting to override that?
![image](https://user-images.githubusercontent.com/12027037/126208177-61b445ff-06eb-452d-b1aa-20dd9dc16ddf.png)

**Comment by michael-andreuzza** [comment]
Let me have a look at that.

I'll get back to you.

/mike

**Comment by michael-andreuzza** [comment]
Hey I got you, they are going to be highlighted with green now, border and also the border.

Let me update and you can reload in around 30 min.

Thank you!

**Comment by gregkonush** [comment]
Perfect, thank you for the quick fix! I verify that it has a contrast color now!

**Comment by michael-andreuzza** [comment]
You welcome Greg.
