### ISSUE TITLE
Low contrast versions of themes

### ISSUE THREAD

**Issue by Milo123459** [michael-andreuzza/wvsc-serendipity#3]

**Comment by michael-andreuzza** [comment]
Hey, would you mind to elaborate the request?

Thank you so much.

/Mike

**Comment by Milo123459** [comment]
Low contrast versions of themes, ie, no contrast between terminal, sidebar, main panel, etc.

**Comment by michael-andreuzza** [comment]
Superb, got ya. Let me look into it. 

Thank you .

**Comment by sokirill** [comment]
![image](https://user-images.githubusercontent.com/2138870/126667887-2f465514-7a7d-439f-9024-39298c82576e.png)
![image](https://user-images.githubusercontent.com/2138870/126667944-bc064b66-77f5-48c5-b301-fbe12a415669.png)

Some good points and comparison.

**Comment by Milo123459** [comment]
I think that it should look like this (the contrast):
![image](https://user-images.githubusercontent.com/50248166/126668944-9f763883-e23f-4539-a235-b2ace5feb2c6.png)

as you can see, no contrast at all.

**Comment by michael-andreuzza** [comment]
Ok, let me see what I can do

**Comment by michael-andreuzza** [comment]
Hey Milo, @Milo123459 I just pushed the low contrast versions. You can update the theme and reload VS Code. It might take some minutes to update though.

**Comment by Milo123459** [comment]
Thanks, will test

**Comment by Milo123459** [comment]
Beautiful!

**Comment by michael-andreuzza** [comment]
really hapy it helped!
