### ISSUE TITLE
Syntax highlighting in JSX / React

### ISSUE THREAD

**Issue by sokirill** [michael-andreuzza/wvsc-serendipity#4]
So here are a few things to look into:
![image](https://user-images.githubusercontent.com/2138870/126668546-bdea2727-25d8-4416-a6b3-8fe4fd9747b6.png)
![image](https://user-images.githubusercontent.com/2138870/126669615-1159ac27-19b6-41d0-9b5c-6cbd6317ac59.png)

- Properties (RED SQUARE) - seems like in serendipity they are **light purple** right now which is not very distinguishable from the function definition purple. Furthermore, when the prop is being called again, it is not highlighted (see example of "result" on the screenshots)
- Components (BLUE SQUARE)- <Image /> usually uses a separate color
- String interpolation inside ${} (PURPLE SQUARE) - same as variable but it seems that variables overall are not highlighted right now - thus they are not being highlighed when used further. (see BASE_URL example on comparison with Dracula). 
- Paths (YELLOW SQUARE) - have been resolved to orange already as what I have seen from the last update.

**Comment by michael-andreuzza** [comment]
I will be looking into it Next week Kirill. Thank you so much.

**Comment by michael-andreuzza** [comment]
Hey @sokirill, I will be closing this issue because no one else has mentioned. I will take it as a personal preference and I will recommend using your json file to adjust it.

Thank you so much.
