### ISSUE TITLE
BD103

### ISSUE THREAD

**Issue by whippingdot** [michael-andreuzza/wvsc-serendipity#6]
@BD103 bro i found this theme on dev.to I think...I didn't even know you helped make it. Amazing job bro! I love it

Can you maybe create the website that your image is based off? I know it is only a Figma design, but that website would look fire if you made it, and it would be easier to test out the theme on the website (with like maybe a 'fake' vs code that changes when you toggle the theme).

Anyway, your theme was the first change from one dark pro in almost a year so good job making me leave one dark pro!

**Comment by BD103** [comment]
I made a PR after seeing you star it. (#5) I'm not taking credit for Michael Andreuzza's hard work. :)

**Comment by whippingdot** [comment]
oh ok lol
