### ISSUE TITLE
Python docstrings not using a subtle gray color

### ISSUE THREAD

**Issue by fredrikaverpil** [michael-andreuzza/wvsc-serendipity#7]
Hi and thanks for an amazing theme! :heart:

I noticed Python docstrings are colored as purple. This not only takes up very much focus from the actual code but all other comments seems like they are intended to be gray. I've added a small workaround for now in my `settings.json` but maybe this is something which should be fixed in the theme itself?

```json
{
    "editor.tokenColorCustomizations": {
        "[Serendipity Dark]": {
            "textMateRules": [{
                "scope": "string.quoted.docstring.multi.python",
                "settings": {
                    "foreground": "#5c6773"
                }
            }]
        }
    }
}
```

You can reproduce this by just looking at a python script with a docstring:

```python
def x():
    """Some docstring here."""
    return None
```

**Comment by michael-andreuzza** [comment]
Hey Fredrik,

I have been looking into it and this is how it looks now.
![image](https://user-images.githubusercontent.com/34077176/142297637-84fcfd82-6a88-49e5-9040-6daff69a9c50.png)


I hope this helps.

/Mike

**Comment by fredrikaverpil** [comment]
That's awesome, many thanks! 👍

**Comment by michael-andreuzza** [comment]
> That's awesome, many thanks! 👍

Det var så lite!
