### ISSUE TITLE
Black quotes

### ISSUE THREAD

**Issue by whippingdot** [michael-andreuzza/wvsc-serendipity#8]
Why am I getting this?
![image](https://user-images.githubusercontent.com/64354499/142444859-af60cfaf-e0c4-4ee6-8538-95bb3f879dbb.png)

It looks horrible if it was deliberate I recommend you change that...

**Comment by whippingdot** [comment]
BTW this is Dark Italics - Dark works perfectly fine.

**Comment by michael-andreuzza** [comment]
can you elaborate on "it looks horrible"?

It does not help me to allocate the issue.
Thank you.

**Comment by michael-andreuzza** [comment]
you can update un a while and it should be corrected:
![image](https://user-images.githubusercontent.com/34077176/142492758-e0520bde-2d36-471d-9fb9-c0b574d54962.png)

For any reason that code was #000...

**Comment by michael-andreuzza** [comment]
closing because is fixed.
